from app.models import db, Deck


def seed_decks():
    deck1 = Deck(title="Easy SQL", categoryId=1, userId=3)
    deck2 = Deck(title="Medium SQL", categoryId=1, userId=3)
    deck3 = Deck(title="Hard SQL", categoryId=1, userId=3)
    deck4 = Deck(title="Easy Docker", categoryId=4, userId=2)
    deck5 = Deck(title="Medium Docker", categoryId=4, userId=2)
    deck6 = Deck(title="Hard Docker", categoryId=4, userId=1)
    deck7 = Deck(title="Easy HTML", categoryId=5, userId=1)
    deck8 = Deck(title="Medium HTML", categoryId=5, userId=1)
    deck9 = Deck(title="Hard HTML", categoryId=5, userId=2)
    deck10 = Deck(title="Easy JavaScript", categoryId=6, userId=1)
    deck11 = Deck(title="Easy Linux", categoryId=8, userId=2)
    deck12 = Deck(title="Medium Linux", categoryId=8, userId=2)
    deck13 = Deck(title="Hard Linux", categoryId=8, userId=2)
    deck14 = Deck(title="Easy PHP", categoryId=9, userId=1)
    deck15 = Deck(title="Medium PHP", categoryId=9, userId=1)
    deck16 = Deck(title="Hard PHP", categoryId=9, userId=1)
    deck17 = Deck(title="Easy Kubernetes", categoryId=7, userId=2)
    deck18 = Deck(title="Medium Kubernetes", categoryId=7, userId=2)
    deck19 = Deck(title="Hard Kubernetes", categoryId=7, userId=2)
    deck20 = Deck(title="Easy DevOps", categoryId=3, userId=1)
    deck21 = Deck(title="Easy CMS", categoryId=2, userId=1)
    deck22 = Deck(title="Medium CMS", categoryId=2, userId=1)
    deck23 = Deck(title="Hard CMS", categoryId=2, userId=1)

    db.session.add(deck1)
    db.session.add(deck2)
    db.session.add(deck3)
    db.session.add(deck4)
    db.session.add(deck5)
    db.session.add(deck6)
    db.session.add(deck7)
    db.session.add(deck8)
    db.session.add(deck9)
    db.session.add(deck10)
    db.session.add(deck11)
    db.session.add(deck12)
    db.session.add(deck13)
    db.session.add(deck14)
    db.session.add(deck15)
    db.session.add(deck16)
    db.session.add(deck17)
    db.session.add(deck18)
    db.session.add(deck19)
    db.session.add(deck20)
    db.session.add(deck21)
    db.session.add(deck22)
    db.session.add(deck23)

    db.session.commit()


def undo_decks():
    db.session.execute('TRUNCATE decks RESTART IDENTITY CASCADE;')
    db.session.commit()
