from app.models import db, Deck


def seed_decks():
    deck1 = Deck(title="Easy SQL Questions", categoryId=1, userId=1)
    deck2 = Deck(title="Medium SQL Questions", categoryId=1, userId=1)
    deck3 = Deck(title="Hard SQL Questions", categoryId=1, userId=1)
    deck4 = Deck(title="Easy Docker Questions", categoryId=4, userId=2)
    deck5 = Deck(title="Medium Docker Questions", categoryId=4, userId=2)
    deck6 = Deck(title="Hard Docker Questions", categoryId=4, userId=2)
    deck7 = Deck(title="Easy HTML Questions", categoryId=5, userId=2)
    deck8 = Deck(title="Medium HTML Questions", categoryId=5, userId=2)
    deck9 = Deck(title="Hard HTML Questions", categoryId=5, userId=2)
    deck10= Deck(title="Easy JavaScript Questions", categoryId=6, userId=2)
    deck11= Deck(title="Easy Linux Questions", categoryId=8, userId=2)
    deck12= Deck(title="Medium Linux Questions", categoryId=8, userId=2)
    deck13= Deck(title="Hard Linux Questions", categoryId=8, userId=2)
    deck14= Deck(title="Easy PHP Questions", categoryId=9, userId=2)
    deck15= Deck(title="Medium PHP Questions", categoryId=9, userId=2)
    deck16= Deck(title="Hard PHP Questions", categoryId=9, userId=2)
    deck17= Deck(title="Easy Kubernetes Questions", categoryId=7, userId=2)
    deck18= Deck(title="Medium Kubernetes Questions", categoryId=7, userId=2)
    deck19= Deck(title="Hard Kubernetes Questions", categoryId=7, userId=2)
    deck20= Deck(title="Easy DevOps Questions", categoryId=3, userId=2)
    deck21= Deck(title="Easy CMS Questions", categoryId=2, userId=2)
    deck22= Deck(title="Medium CMS Questions", categoryId=2, userId=2)
    deck23= Deck(title="Hard CMS Questions", categoryId=2, userId=2)


    db.session.add(deck1)
    db.session.add(deck2)
    db.session.add(deck3)
    db.session.add(deck4)
    db.session.add(deck5)
    db.session.add(deck6)
    db.session.add(deck7)
    db.session.add(deck8)
    db.session.add(deck9)
    db.session.add(deck10)
    db.session.add(deck11)
    db.session.add(deck12)
    db.session.add(deck13)
    db.session.add(deck14)
    db.session.add(deck15)
    db.session.add(deck16)
    db.session.add(deck17)
    db.session.add(deck18)
    db.session.add(deck19)
    db.session.add(deck20)
    db.session.add(deck21)
    db.session.add(deck22)
    db.session.add(deck23)


    db.session.commit()


def undo_decks():
    db.session.execute('TRUNCATE decks RESTART IDENTITY CASCADE;')
    db.session.commit()
