"""empty message

Revision ID: 2e314c49a777
Revises: 811ea8547a7e
Create Date: 2021-07-21 20:01:51.719443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e314c49a777'
down_revision = '811ea8547a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('decks_title_key', 'decks', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('decks_title_key', 'decks', ['title'])
    # ### end Alembic commands ###
