"""empty message

Revision ID: 4a029e004a56
Revises: e6b00d6be10a
Create Date: 2021-07-21 09:42:26.323925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a029e004a56'
down_revision = 'e6b00d6be10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_deckId_fkey', 'cards', type_='foreignkey')
    op.drop_column('cards', 'deckId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('deckId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('cards_deckId_fkey', 'cards', 'decks', ['deckId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
