"""empty message

Revision ID: 12a4ee833b4f
Revises: 2e314c49a777
Create Date: 2021-07-25 11:23:34.159824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a4ee833b4f'
down_revision = '2e314c49a777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'question',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=5000),
               existing_nullable=False)
    op.alter_column('cards', 'answer',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=5000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'answer',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('cards', 'question',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
